bot_defaults: &bot_defaults
  adapter: mysql2
  pool: 5
  host: localhost
  username: root
  flags: 65536

bot_development:
  database: bot_development
  <<: *bot_defaults

bot_test:
  database: bot_test
  <<: *bot_defaults
